services:
  ijazah-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ijazah-frontend
    restart: unless-stopped
    ports:
      - "5174:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"